"""
Script de peuplement de la base de données Oracle.
À exécuter une seule fois pour créer la table et insérer les FAQs.

Usage : python populate_db.py
"""

import json
import cx_Oracle
from db import get_connection

# ──────────────────────────────────────────────────────────────────
# Création de la table FAQ (si elle n'existe pas déjà)
# ──────────────────────────────────────────────────────────────────
SQL_CREATE_TABLE = """
    CREATE TABLE faq (
        id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        keyword  VARCHAR2(100)  NOT NULL,
        question VARCHAR2(500)  NOT NULL,
        reponse  VARCHAR2(2000) NOT NULL
    )
"""

SQL_INSERT = """
    INSERT INTO faq (keyword, question, reponse)
    VALUES (:keyword, :question, :reponse)
"""


def table_existe(cursor, nom_table: str) -> bool:
    """Vérifie si une table existe déjà dans le schéma courant."""
    cursor.execute(
        "SELECT COUNT(*) FROM user_tables WHERE table_name = :nom",
        {"nom": nom_table.upper()}
    )
    return cursor.fetchone()[0] > 0


def creer_table(cursor):
    """Crée la table FAQ si elle n'existe pas."""
    if table_existe(cursor, "faq"):
        print("[INFO] La table FAQ existe déjà, création ignorée.")
    else:
        cursor.execute(SQL_CREATE_TABLE)
        print("[OK] Table FAQ créée.")


def inserer_faqs(cursor, faqs: list):
    """Insère toutes les FAQs dans la table."""
    nb_inseres = 0
    for faq in faqs:
        try:
            cursor.execute(SQL_INSERT, {
                "keyword":  faq["keyword"],
                "question": faq["question"],
                "reponse":  faq["reponse"]
            })
            nb_inseres += 1
        except cx_Oracle.IntegrityError as e:
            print(f"[ERREUR] Doublon ignoré pour : {faq['keyword']} — {e}")

    print(f"[OK] {nb_inseres} FAQs insérées.")
    return nb_inseres


def main():
    # Chargement des données JSON
    print("[DÉPART] Chargement du fichier JSON...")
    with open("data/faq_universitaire.json", "r", encoding="utf-8") as f:
        faqs = json.load(f)
    print(f"[INFO] {len(faqs)} entrées trouvées dans le fichier JSON.")

    # Connexion à Oracle
    print("[CONNEXION] Connexion à Oracle...")
    conn = get_connection()
    cursor = conn.cursor()

    try:
        creer_table(cursor)
        nb = inserer_faqs(cursor, faqs)
        conn.commit()
        print(f"\n✅ Peuplement terminé : {nb} FAQs insérées dans Oracle.")
    except Exception as e:
        conn.rollback()
        print(f"\n❌ Erreur lors du peuplement : {e}")
    finally:
        cursor.close()
        conn.close()


if __name__ == "__main__":
    main()
